### ISSUE TITLE
File manager issues and improvements tracker

### ISSUE THREAD

**Issue by Stoppedpuma** [woelper/oculante#515]
# Issues:

- [ ] Some thumbnails refuse to generate
- [ ] Generation of thumbnails is slow
- [ ] Performance is horrible in directories with thousands of images
- [ ] Folder buttons and text seem to be incorrect in the file list

# Improvements:

- [ ] Resizing the window should only work in increments of how many thumbnails can be present
- [ ] Make the colour of the file name background dependent on theme
- [ ] Add blur to allow more transparency (see attached image, values are black/white at 10% opacity, white text 65% opacity)
- [ ] Experiment with jpeg or jpeg-xl reduce thumbnail file size
- [ ] Replace the plain text of a non-loaded thumbnail (proof of concept in second attached image, will likely be improved later)
    
![image](https://github.com/user-attachments/assets/71658798-5742-4990-9be7-87b574c67fd2)
![image](https://github.com/user-attachments/assets/8097af05-2626-4973-b537-639f745e88fa)

**Comment by B-LechCode** [comment]
I'd like to have the option to edit the path via keyboard/copy paste :)

**Comment by Stoppedpuma** [comment]
> I'd like to have the option to edit the path via keyboard/copy paste :)

I have already mentioned this so it should be added when sorting filters come around! I've also had the idea for a "right click" menu for the thumbnails and bookmarks but these aren't possible at the moment since overlays (the file manager is currently a pop-up) can't seem to create other overlays / pop-ups. Expect these as well whenever it's possible!

**Comment by B-LechCode** [comment]
@Stoppedpuma 
I have discovered a new issue: If a directory contains many images, the RAM usage explodes. Maybe this is because of thumbnail generation?
Discovered this while maneuvering into the tests directory after running your script. My 32 Gigs got blown away.

**Comment by Stoppedpuma** [comment]
> @Stoppedpuma
I have discovered a new issue: If a directory contains many images, the RAM usage explodes. Maybe this is because of thumbnail generation?
Discovered this while maneuvering into the tests directory after running your script. My 32 Gigs got blown away.

Great catch! The performance is pretty bad overall at the moment as loading a directory with several thousand images makes Oculante basically unusable if it doesn't just crash right away. This definitely needs to be improved one way or another prior to the next release if we're including it.

@woelper going off the assumption that all thumbnails are loaded at the same time, a better option we could do here is to only load thumbnails for **visible** thumbnails + 1 row in each direction to prevent the user from seeing them being loaded.

**Comment by Stoppedpuma** [comment]
@B-LechCode Since you mentioned in a previous issue that you had some things you found missing, would you mind compiling a list? I'll try my best to implement these into the design if needed!

**Comment by B-LechCode** [comment]
> [@B-LechCode](https://github.com/B-LechCode) Since you mentioned in a previous issue that you had some things you found missing, would you mind compiling a list? I'll try my best to adapt any designs if needed.

For me these functions are missing:
- Pressing Ctrl+L usually jumps to the address bar and lets me edit the path via keyboard
- Standard functions like renaming, moving, folder creation, file pasting
- Backspace to move one step back
- Mouse buttons forward/backward
[...] Maybe some of the mentioned points are implemented, I'm compiling from my memories. Will try to use the integrated file dialog the next days/weeks and will add more or remove.

General thought:
It's hard to implement a file dialog with the functions a user is familiar with in his chosen OS. That's why I would always rely on the OS native one - these are proven, well understood and maintained. Implementing all the stuff I mentioned is PITA, I think. 
So I'd suggest to only add the functions other users complain about - I'm okay with using the OS native dialog and maybe a "special" user.

**Comment by Stoppedpuma** [comment]
Those are all great to have! One thing which can't be done at the moment is functions like renaming or whatever unless we want it bound to a key? Originally, a context menu was going to display whenever clicking a bookmark or thumbnail with options like rename, delete, favourite, etc. This hasn't been done yet because of an egui limitation with not being able to have more than one overlay (which the file manager is).

The keybinds you mention are all pretty common and I agree are a bit strange to not have. I think these should all be customisable since a few of are commonly changed like search regularly being Ctrl+L or Ctrl+F in most GUI apps.

I've added several keybinds to the improvements list of this issue.
